### PR TITLE
Fix 170

### LINKED ISSUE #170: Wrong password message when no connection
When the connection to the server fails when a user is trying to log into the application, the user is told that he does not have the right password/username instead of connection lost.

### PR DESCRIPTION
**Pull request by Vino98**
Vi har lavet fix 170. Det hele virker som det skal i weekplaner applikation. Vi har dog ikke lavet en decideret test under tests til at teste internet connection og server connection. Vi ved ikke, om det er muligt at lave en decideret test til at teste internet connection og server connection. Hvis det er muligt, så kan der evt laves et nyt issue.

### CODE REVIEW

File: lib/screens/login_screen.dart [hunk 1]
```diff
@@ -47,22 +49,48 @@ class LoginScreenState extends State<LoginScreen> {
...
-          builder: (BuildContext context) {
-            return const GirafNotifyDialog(
-                title: 'Fejl',
-                description: 'Forkert brugernavn og/eller adgangskode',
-                key: Key('WrongUsernameOrPassword'));
-          });
-    }
+    // Checking internet connection, if true check server connection
+    checkInternetConnection().then((bool value) {
+      if (value == true) {
```
Comment (mathiasandresen) [inline lib/screens/login_screen.dart]:
```suggestion
    checkInternetConnection().then((bool hasInternetConnection) {
      if (hasInternetConnection) {
```

File: lib/screens/login_screen.dart [hunk 2]
```diff
@@ -47,22 +49,48 @@ class LoginScreenState extends State<LoginScreen> {
...
+
+        // Checking server connection, if true check username/password
+        checkServerConnection().then((bool value1) {
+          if (value1 == true) {
```
Comment (mathiasandresen) [inline lib/screens/login_screen.dart]:
```suggestion
        checkServerConnection().then((bool hasServerConnection) {
          if (hasServerConnection) {
```

File: lib/screens/login_screen.dart (hunk 1 above)
Comment (mathiasandresen) [reply lib/screens/login_screen.dart]: makes the code more readable

File: lib/screens/login_screen.dart (hunk 2 above)
Comment (mathiasandresen) [reply lib/screens/login_screen.dart]: makes the code more readable

File: lib/screens/login_screen.dart (hunk 1 above)
Comment (christianhurley) [inline lib/screens/login_screen.dart]: value is not descriptive. Look at mathiasandresen's suggestion

File: lib/screens/login_screen.dart (hunk 2 above)
Comment (christianhurley) [inline lib/screens/login_screen.dart]: value1 is not descriptive. Look at mathiasandresen's suggestion

**Review by christianhurley — CHANGES_REQUESTED** [review]
A bit of refactoring to make it easier to read.

File: lib/screens/login_screen.dart [hunk 3]
```diff
@@ -212,4 +240,38 @@ class LoginScreenState extends State<LoginScreen> {
...
   }
+
+  /// Function to test connection to server,
+  /// it both checks for DEV API connection and to PROD API connection
+  Future<bool> checkServerConnection() async {
+    final String loginUrl = environment.getVar<String>('SERVER_HOST');
+    try {
+      final http.Response loginResponse =
+      await http.get(loginUrl).timeout(const Duration(seconds: 10));
+      if (loginResponse.statusCode == 200) {
```
Comment (MrPekar98) [inline lib/screens/login_screen.dart:258]: Would prefer some sort of structure of error codes so that we don't have to use literals. Either declare a constant SOME_CONSTANT with an appropriate name for error 200, or create a list of error constants in a file we can refer to, or simply tell the type of error in a comment above.

**Review by christianhurley — APPROVED** [review]

**Review by MrPekar98 — APPROVED** [review]
