### PR TITLE
fixes_305

### LINKED ISSUE #305: Application crashes when more than 3 weekplans are marked in 'edit'-mode.
**Describe the bug**
After navigating to a list of weekplans belonging to a citizen, if the 'edit'-button is pressed and 4 weekplans are marked,  an error screen is shown.

**To Reproduce**
1. Go to a list of weekplans for any citizen.
2. Click on the 'edit'-button.
3. Mark 4 weekplans.
4. Enjoy!

**Expected behavior**
User should be able to mark more than 3 weekplans.

**Actual behavior**
Error screen.

**Screenshots**
See video in .zip file.
[EditWeekplanCrashBug.zip](https://github.com/aau-giraf/weekplanner/files/4257714/EditWeekplanCrashBug.zip)

**Environment (please complete the following information):**
Observed in emulator and on phone (Android).

### PR DESCRIPTION
**Pull request by nicolaibjerring**
Fixes #305  

Fixed bug by removing duplicate keys for container widgets. Each time a week plan was marked the
key for the specific week plan was set to 'isSelectedKey'. This resulted in all week plans
having the same key ('isSelectedKey') when marking multiple, which is invalid and threw an exception in the flutter library.

### CODE REVIEW

**Review by mathiasandresen — COMMENTED** [review]
@aau-giraf/sw611f20 you have been assigned this. Here's your checklist. 
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [x] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**

- [x] Are names meaningful and self-documenting?
- [x] Is it understandable, by reading the code, what it does?
- [x] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [x] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**

For this part, open the app, and test:

- [x] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**

- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

**Review by mathiasandresen — COMMENTED** [review]
@aau-giraf/sw614f20 you have been assigned this. Here's your checklist. 
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [x] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**

- [ ] Are names meaningful and self-documenting?
- [x] Is it understandable, by reading the code, what it does?
- [x] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [x] Is it understandable, by reading the tests, what they do?
- [x] Do the tests cover sensible cases? Both happy paths and exception paths?
- [x] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [x] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**

For this part, open the app, and test:

- [x] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**

- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

File: test/screens/weekplan_selector_screen_test.dart [hunk 1]
```diff
@@ -175,14 +175,19 @@ void main() {
         .pumpWidget(MaterialApp(home: WeekplanSelectorScreen(mockUser)));
     await tester.pumpAndSettle();
 
-    expect(find.text('weekModel1'), findsOneWidget);
+    expect(find.byKey(Key(weekModel1.name)), findsOneWidget);
+    // Before we mark the week plan weekModel1 we check that it
+    // is in fact not marked
+    expect(bloc.getMarkedWeekModels().contains(weekModel1), false);
```
Comment (EsbenNedergaard) [inline test/screens/weekplan_selector_screen_test.dart:181]: Not sure that i like that this is one test because you have so many expects in there i would probably make another test where we do this check:
expect(bloc.getMarkedWeekModels().contains(weekModel1), false);
Because that makes debugging a lot easier.

File: test/screens/weekplan_selector_screen_test.dart [hunk 2]
```diff
@@ -175,14 +175,19 @@ void main() {
...
 
     await tester.tap(find.byTooltip('Rediger'));
     await tester.pumpAndSettle();
     await tester.tap(find.byKey(Key(weekModel1.name)));
     await tester.pumpAndSettle();
 
-    expect(find.byKey(const Key('isSelectedKey')), findsOneWidget);
+    // After we have marked the week plan weekModel1 we check that it
+    // is in fact marked
+    expect(bloc.getMarkedWeekModels().contains(weekModel1), true);
```
Comment (EsbenNedergaard) [inline test/screens/weekplan_selector_screen_test.dart:190]: Also i would argue this test is not really correct, because you test the bloc instead of the testing the screen itself by accesing the bloc.getMarkedWeekModels, see if you cannot change this test by looking into what is changed when a week model is marked (if a new type of widget is created) and see if you can find those instead.

File: test/screens/weekplan_selector_screen_test.dart [hunk 3]
```diff
@@ -214,24 +219,51 @@ void main() {
...
 
-    await tester.tap(find.byKey(Key(weekModel2.name)));
+    await tester.tap(find.byTooltip('Rediger'));
     await tester.pumpAndSettle();
 
-    expect(find.byKey(const Key('isSelectedKey')), findsNWidgets(2));
+    // Checks that after the "Rediger"-button has been pressed, the
+    // week plans are not marked any more
+    expect(bloc.getMarkedWeekModels().contains(weekModel1), false);
+    expect(bloc.getMarkedWeekModels().contains(weekModel2), false);
```
Comment (EsbenNedergaard) [inline test/screens/weekplan_selector_screen_test.dart:242]: Same as above you use the bloc not the screen

File: test/screens/weekplan_selector_screen_test.dart [hunk 4]
```diff
@@ -214,24 +219,51 @@ void main() {
...
+
+    // Checks that the marked week model is in fact marked
+    expect(bloc.getMarkedWeekModels().contains(weekModel1), true);
+
+    await tester.tap(find.byKey(Key(weekModel1.name)));
+    await tester.pumpAndSettle();
+
+    // Checks that after marking/tapping the week plan again, the
+    // week plan are not marked any more
+    expect(bloc.getMarkedWeekModels().contains(weekModel1), false);
```
Comment (EsbenNedergaard) [inline test/screens/weekplan_selector_screen_test.dart:267]: same as above

**Review by EsbenNedergaard — CHANGES_REQUESTED** [review]
You seem to be testing the bloc instead of testing the actual screen, see other comments for more details

File: test/screens/weekplan_selector_screen_test.dart (hunk 2 above)
Comment (nicolaibjerring) [reply test/screens/weekplan_selector_screen_test.dart:190]: We can not test the screen as for as we know.

Comment (nicolaibjerring) [reply test/screens/weekplan_selector_screen_test.dart:190]: Created a new issue for testing the screen: https://github.com/aau-giraf/weekplanner/issues/355

**Review by EsbenNedergaard — DISMISSED** [review]

File: test/screens/weekplan_selector_screen_test.dart [hunk 5]
```diff
@@ -214,24 +219,51 @@ void main() {
...
     await tester.pumpAndSettle();
 
-    expect(find.byKey(const Key('isSelectedKey')), findsNWidgets(2));
+    // Checks that after the "Rediger"-button has been pressed, the
+    // week plans are not marked any more
+    expect(bloc.getMarkedWeekModels().contains(weekModel1), false);
+    expect(bloc.getMarkedWeekModels().contains(weekModel2), false);
+  });
+
+  testWidgets('Marking activity and marking it again unmarks it',
```
Comment (tdybda17) [inline test/screens/weekplan_selector_screen_test.dart]:
```suggestion
  testWidgets('Clicking a marked activity should unmark it',
```

File: test/screens/weekplan_selector_screen_test.dart (hunk 4 above)
Comment (tdybda17) [reply test/screens/weekplan_selector_screen_test.dart]: I see no problem with a large test containing multiple expectations

**Review by tdybda17 — CHANGES_REQUESTED** [review]

**Review by tdybda17 — APPROVED** [review]

**Review by EsbenNedergaard — APPROVED** [review]
