### PR TITLE
ReleaseFix to 541

### LINKED ISSUE #541: Overwrite dialog when copying week plan is only displayed if the are activities on the week plan
**Describe the bug**
When copying a week plan, the overwrite dialog is only displayed, if the existing week plan(s) have activities on them.

**To Reproduce**
1. Go to week plan selector screen.
2. Click on the edit icon.
3. Select a week plan.
4. Press "Kopiér".
5. Press "Denne borger".
6. Change the title to something unique.
7. Press "Kopier ugeplan".

**Expected behavior**
A dialog opens asking to confirm overwriting the existing plan.

**Actual behavior**
The title of the copied week plan is changed to the title chosen in step 6.

**Screenshots**
N/A

**Environment (please complete the following information):**
- OS: N/A
- Emulator: N/A
- Phone: N/A
- APK Version: N/A

**Additional context**
Also applicable when copying to other citizens.

### PR DESCRIPTION
**Pull request by Laexander**
Fixes #541 
There is one instance where naming the weekplan "`weekYear` - `weekNumber`" will still reproduce the bug. 
However, solving this would require bigger changes to the web-api and how it handles not finding a week plan for a user, and after a discussion with PO was moved to a new issue. 
New issue created for fixing this #547

### CODE REVIEW

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw611f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw612f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

**Review by aerlingsson — APPROVED** [review]

File: lib/blocs/copy_weekplan_bloc.dart [hunk 1]
```diff
@@ -81,10 +81,19 @@ class CopyWeekplanBloc extends ChooseCitizenBloc {
     if(response.days == null){
       return false;
     }
+
     for (WeekdayModel weekDay in response.days) {
       daysAreEmpty = daysAreEmpty && weekDay.activities.isEmpty;
     }
 
+    ///Checks whether the name of the week model is different from the default
```
Comment (klogeat) [inline lib/blocs/copy_weekplan_bloc.dart:89]: missing space in beginning of comment

**Review by klogeat — APPROVED** [review]
