### PR TITLE
Release fix/253

### LINKED ISSUE #253: Second change to guardian mode prompt does not give error message when given wrong password
**Describe the bug**
When attempting to switch to guardian mode a second time with a incorrect password (or empty password) no error dialog box is shown.
Also after this bug occurs one cannot switch to guardian mode with the right password; it is now stuck on the loading spinner.

**To Reproduce**
1. Go to any weekplan and change to citizen mode
2. Click on change to guardian mode
3. Click on change to citizen mode
4. Try to change to guardian mode with wrong/empty password
5. Notice that no dialog box tells you that the password was wrong and you can no longer change to guardian mode with correct password

**Expected behavior**
The dialog box should appear any time a wrong password is given and then allow the user to fix the password, such that the user can switch to guardian mode.

**Actual behavior**
No dialog box is shown and the user is now stuck in citizen mode

**Environment (please complete the following information):**
- OS: android 
- Emulator: pixel_2_API_28

### PR DESCRIPTION
**Pull request by User12837985123**
This closes #253.

### CODE REVIEW

File: lib/blocs/toolbar_bloc.dart [hunk 1]
```diff
@@ -409,9 +409,9 @@ class ToolbarBloc extends BlocBase {
     showLoadingSpinner(context, false, _showFailureDialog, 2000);
     _loginStatus = false;
     _currentContext = context;
-    _authBloc.authenticateFromPopUp(username, password);
+
     // Skip 1, since we should skip the seeded value.
-    _authBloc.loginAttempt.listen((bool snapshot) {
+    _authBloc.loginAttempt.skip(1).listen((bool snapshot) {
```
Comment (Tricky12321) [inline lib/blocs/toolbar_bloc.dart:428]: If you need to skip the seeded value, why is it seeded?

File: test/screens/weekplan_screen_test.dart [hunk 2]
```diff
@@ -549,6 +513,47 @@ void main() {
...
+          done.complete();
+        });
+
+        // Only thing that should be popped is the loading spinner.
+        verify(observer.didPop(any, any)).called(1);
+
+        expect(find.byKey(const Key('WrongPasswordDialog')),
+            findsOneWidget);
+
+        await done.future;
```
Comment (Tricky12321) [inline test/screens/weekplan_screen_test.dart:556]: This is a very big test, consider making it into more smaller tests

File: test/screens/weekplan_screen_test.dart [hunk 3]
```diff
@@ -561,9 +566,8 @@ void main() {
     ));
     await tester.pumpAndSettle();
 
-    // We need to skip 2 this time, first skip the seeded value
-    // second skip the switch to citizen mode (which is part of the arrange
-    // step for this test)
+    // Skip twice, first for the seeded value, second for the
+    // setMode call made during arranging of this test case.
     authBloc.mode.skip(2).listen((WeekplanMode mode) async {
```
Comment (Tricky12321) [inline test/screens/weekplan_screen_test.dart:573]: Again if you need to skip the seeded value, why is it seeded?

**Review by Tricky12321 — CHANGES_REQUESTED** [review]

File: test/screens/weekplan_screen_test.dart (hunk 3 above)
Comment (User12837985123) [reply test/screens/weekplan_screen_test.dart:573]: I am not the original author of the test, but I think it is seeded to indicate that the default value of the stream is GuardianMode, as the app is always started in Guardian mode.

Comment (Tricky12321) [reply test/screens/weekplan_screen_test.dart:573]: Okay

File: lib/blocs/toolbar_bloc.dart (hunk 1 above)
Comment (User12837985123) [reply lib/blocs/toolbar_bloc.dart:428]: I really don't know why, but if skip(1) is not there, the error of #253 happens...

Comment (Tricky12321) [reply lib/blocs/toolbar_bloc.dart:428]: Okay, guess we will leave it then

File: test/screens/weekplan_screen_test.dart (hunk 2 above)
Comment (User12837985123) [reply test/screens/weekplan_screen_test.dart:556]: Tried, but they are still pretty big due to the arrange and acting parts of the test

Comment (Tricky12321) [reply test/screens/weekplan_screen_test.dart:556]: In this test you test if the error dialog shows. This can be done using a mock screen

Consider writing a test dedicated to testing the dialog, and the parts regarding that.
Instead of pumping the weekplan screen, pump a mockscreen only containing the dialog for entering the password and test on that

**Review by B97theFallen — DISMISSED** [review]

**Review by B97theFallen — APPROVED** [review]

**Review by Tricky12321 — APPROVED** [review]
